vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        books:
            upload_destination: '%kernel.project_dir%/public/uploads/images/books'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer